global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka_server:9092']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper_server:2181']

  - job_name: 'redis'
    static_configs:
      - targets: ['cache_rediska:6379']
